# Generated by Django 2.2.4 on 2019-08-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='specification',
            field=models.ManyToManyField(blank=True, to='accounts.Specification'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='total_experience',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
